### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by KanzaTahreem** [KanzaTahreem/Recipe-App#13]
### _Hey Reviewer_ 👋

Regarding this issue, we covered the following [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md) 🔽

- Create an empty repository for your group project.
- Open the GitHub project (Kanban board) in your team repo
- Create tasks on your Kanban board based on the [project requirements](./buisness_requirements.md).
- Each task should be a separate card with descriptive title and number of points in the `[Xpt]` prefix
- Each of the team members should assign themselves to the cards.
- Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees. 
- [Open a new issue in your repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue) and send it for review

### _Project Link_ 🔗
Here is the link for [Kanban board](https://github.com/KanzaTahreem/Recipe-App/projects/1) created for the project

### _Group Members_ 😄
@rbreva 
@KanzaTahreem

**Comment by cynthiainga** [comment]
Hi @KanzaTahreem & @rbreva, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights

- [ ] Descriptive issue ✔️ 
- [ ] Setup correctly the Kanban board ✔️ 

## Required Changes ♻️

- [ ] As required in the project all the cards should have a description but your #10 and #11 don’t have a description, kindly add a description to the two issues 🙃 🙃 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Mihndim2020** [comment]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi Team, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good job with issue summary

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
